# Generated by Django 4.1.3 on 2022-12-21 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='streetAddress',
            new_name='address',
        ),
    ]
