# Generated by Django 4.1.3 on 2023-01-19 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_product_image2_product_image3_product_image4_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeCarouselImage',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
