# Generated by Django 4.1.3 on 2023-02-22 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_homecarouselimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(blank=True, choices=[('Poor', 'Poor'), ('Good', 'Good'), ('Very Good', 'Very Good'), ('New', 'New')], max_length=20, null=True),
        ),
    ]
